version: "3.7"
services:
  mysql:
    image: mysql:8.0
    container_name: d4mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_USER: ${DB_MYSQL_USERNAME}
      SERVICE_NAME: mysql
    networks:
      - d4

  nginx:
    image: nginx:alpine
    container_name: d4-nginx
    restart: unless-stopped
    depends_on:
      - ta-10
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/sites-available/:/etc/nginx/sites-available/
      - ./nginx/sites-available/:/etc/nginx/sites-enabled/
      - ./dhparam:/etc/nginx/dhparam
      - ./certbot/conf/:/etc/nginx/ssl/
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
      - ./ta-10/staticfiles:/var/www/ta-10/staticfiles
      - /home/ubuntu/ta-01/app/staticfiles:/var/www/ta-1/staticfiles
      - /home/ubuntu/ta-01/app/mediafiles:/var/www/ta-1/mediafiles
    networks:
      - d4

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email panjaitanandree@gmail.com --agree-tos --no-eff-email -d ta1.d4trpl19.net
    volumes:
      - ./certbot/conf/:/etc/letsencrypt
      - ./certbot/logs/:/var/log/letsencrypt
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    networks:
      - d4

  ta-10:
    image: andreejait/ta10:latest-amd64
    container_name: ta-10-service
    env_file:
      - ta-10/.env
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./ta-10/staticfiles:/ta10/static
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DOMAIN_TA_10}
    networks:
      - d4

networks:
  d4:
    driver: bridge
